name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Enable manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    env:
      ENVIRONMENT: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest test_open_library.py  # Run this first
          pytest test_api.py            # Run this second

#      # Docker steps
#      - name: Build Docker image
#        run: docker build . -t my-app
#
#      - name: Run tests in Docker
#        run: docker run my-app